### ISSUE TITLE
Advice on Subcategories

### ISSUE THREAD

**Issue by ghost** [yoonic/nicistore#8]
I'm just getting into this piece of code (Great Work!) and I'm wanting to add subcategories. Any suggestions on how to go about this? I'd be looking to have Brand as the main category, then Specific Phones (We're a cellphone shop). Also looking to add Variants. I just need an overall idea of how to go about this.

Thanks.

**Comment by andrecrt** [comment]
Hi!

Thanks for your feedback, interest on the project and looking forward to seeing your store powered by it!

The concept of Category/Collection is something up to the storefront, as you might have already noticed. On the API/Atlas (https://github.com/yoonic/atlas) side of things, there's only the concept of "Collections" which can be used to group Products (and also Contents, Customer, etc if you wish).

In order to achieve sub-categories, you just need to set a parentId to the sub-category (collection) --> https://github.com/yoonic/atlas/blob/master/src/resources/collections/models.js#L87-L89

**Comment by ghost** [comment]
I'm building 2 sites - one backend for corporate customers for the Boss and a simple Disaster Preparedness Kits ecommerce site ( I can show you the latter one once it is up!).

**Comment by andrecrt** [comment]
Nice! Did my answer help?

**Comment by ghost** [comment]
Yes, I believe it will work. I've been working on creating Variants first. Also, wiped my HD accidentally so I'm starting over a bit. I'll let you know on the subcategories!

**Comment by ghost** [comment]
Question on variants: I'm getting the options to appear on the CartItems. Where will I be storing the Product Variant Data, or is there nothing to hold the Data at the moment and i must create my own StoreHandler?

**Comment by andrecrt** [comment]
The Products entity has the concept of "metadata" that is an object in which you can store whatever sorts of information you want. You can use that for variant logic.

**Comment by mateomorrison** [comment]
@stevecawdery Share that backend with the opensource! Would love to integrate it
