### ISSUE TITLE
Variants

### ISSUE THREAD

**Issue by ghost** [yoonic/nicistore#9]
Hi, I'm trying to associate each item with options (split up the CartItems into distinct items each with an ID). I need to retrieve the user that's adding the items and add the Variants to each item based on user, so that they are stored. I can't seem to store the variant data for each individual product in metadata (I can't figure out how to associate an ID in ProductPage.js with the ID in CartItem.js).

I have been spending many hours playing with Redux, Fluxible and the API on this and having absolutely no success. Please advise me on this.

**Comment by ghost** [comment]
Simply, how would I write to the cart products if I added a field called 'items'? I'm trying to do this from the ProductPage.js. I can't simply use the updateProduct from AdminProductEdit I don't think.

**Comment by ghost** [comment]
Okay, I'm working on the API now, adding tables to DB based on Variants per User. Is there a method to retrieve the current userID / Guest user token  on the frontend (securely) or is this all dealt with on API level?

**Comment by andrecrt** [comment]
Hi,

In regards to you last question about the current userID, you can use the [AccountStore](https://github.com/yoonic/nicistore/blob/master/src/stores/Account/AccountStore.js#L67) for that.

The question about Variants, I'm sorry but I don't think I follow your issue... and since I haven't implemented them it's hard for me to grasp what you are trying to achieve. From my point of view, variants are, first and foremost, just another product like any other with their own SKU, pricing, etc. But since they are almost exactly like each other, differing only on a specific attribute usually (color, size, etc), they may end up having their own product page.

Is this it?

From the top of my head I would use the attribute "metadata" from Products (as you mentioned) to kind of link one product to another. Now.. you could define one of these products as the "parent" and all other are variants of it or you could, in each of the variants, have the whole details about the other products

Product A
Product B (Variant of A)
Product C (Variant of B)

## Option 1 (Product A is parent):
productB.metadata.variantOf = {
    id: ProductA_ID,
    attribute: 'color' // this product differs from A in its color,
    value: 'red'
}

productC.metadata.variantOf = {
    id: ProductA_ID,
    attribute: 'size' // this product differs from A in its color,
    value: 'xl'
}

## Option 2 (All Products have variant information):
productA.metadata.variants = [
    {id: ProductB_ID, attribute: 'color', value: 'red'},
    {id: ProductC_ID, attribute: 'size', value 'xl'}
]

productB.metadata.variants = [
    {id: ProductA_ID, attribute: 'color', value: 'blue'},
    {id: ProductC_ID, attribute: 'size', value 'xl'}
]

productC.metadata.variants = [
    {id: ProductA_ID, attribute: 'color', value: 'blue'},
    {id: ProductB_ID, attribute: 'size', value 's'}
]
